### ISSUE TITLE
error while loading shared libraries?

### ISSUE THREAD

**Issue by tjusxh** [azmathmoosa/azFace#1]
I have the error
"error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory". Please how to solve it？

**Comment by azmathmoosa** [comment]
Check here https://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-opening-microsoft-office-file

Seems like you need to install https://support.microsoft.com/en-us/kb/2999226
